making the blogs through markdown add tags and posts
snaplytic/website pull request #27
Opened 2020-11-28 04:58 UTC by LAEEQ18

on Media Tab click on Tags that are are nested under categories in sidebar.
also add recent posts.

2020-12-13 19:21 UTC, arif-hanif requested changes

2020-12-13 19:21 UTC, arif-hanif commented on src/templates/tags-page.js
> +const tagsPage = ({ pageContext }) => {
components should always be PascalCase; TagsPage

2020-12-13 19:21 UTC, arif-hanif commented on src/templates/tag-post.js
> +const tagPosts = ({ data, pageContext }) => {
components should always be PascalCase; TagPosts

2020-12-13 19:21 UTC, arif-hanif commented on src/pages/media.js
> +  console.log(data)
remove console.log, these should not be checked in

2020-12-13 19:45 UTC, LAEEQ18 commented on src/components/misc/PaginationLinks.js
> +const Pagination = styled.ul`
the code committed below is the styled components that i make for PaginationItem,& PaginationLink that i import from react strap but components are not stylled well kindly guide me about it, that how i make it well performed pagination bar

2020-12-14 14:05 UTC, arif-hanif requested changes

2020-12-14 14:05 UTC, arif-hanif commented on src/components/core/Sidebar.js
> +        </TagLink>
List tags here do not go to a separate page

2020-12-14 14:05 UTC, arif-hanif commented on src/components/core/Sidebar.js
> +    </Card>
Make this a component and remove from page for now, not implemented right now

2020-12-14 14:05 UTC, arif-hanif commented on src/components/core/Sidebar.js
> +    </Card>
Make this a component and remove from page for now, not implemented right now

2020-12-14 14:05 UTC, arif-hanif commented on src/components/core/Sidebar.js
> +// }
Remove not used code

2021-02-20 16:38 UTC, closed without merging