Feature done about and contact page
snaplytic/website pull request #8
Opened 2020-11-12 19:42 UTC by LAEEQ18

fixed the header
get in touch open in new-tab
using styled components
move babel-plugin in dev-dependices etc

2020-11-13 01:24 UTC, arif-hanif commented
@LAEEQ18  remove these files 
![image](https://user-images.githubusercontent.com/8672758/99016406-128a4000-2525-11eb-9329-3fad5bf5d47c.png)

2020-11-13 01:29 UTC, arif-hanif requested changes

2020-11-13 01:29 UTC, arif-hanif commented on package.json
> +    "jquery": "^3.5.1",
remove

2020-11-13 01:29 UTC, arif-hanif commented on package.json
> +
remove white spaces

2020-11-13 01:29 UTC, arif-hanif commented on src/components/Footer.js
> +
white space

2020-11-13 01:29 UTC, arif-hanif commented on src/components/Footer.js
> +
white space

2020-11-13 01:29 UTC, arif-hanif commented on src/components/layout.js
> +
White space

2020-11-13 01:29 UTC, arif-hanif commented on src/components/layout.js
> +    <Footers />
rename this Footer

2020-11-13 01:29 UTC, arif-hanif commented on src/components/layout.js
> +const layout = ({ children }) => (
const Layout

2020-11-13 01:29 UTC, arif-hanif commented on src/components/Footer.js
> +const Footers = () => (
const Footer

2020-11-13 01:29 UTC, arif-hanif commented on src/pages/index.js
> +        <p>
Move privacy policy to seperate component and link from footer, just put place holder of home.

2020-11-13 01:38 UTC, hanif-arif commented
@LAEEQ18 navbar is way to large when you scroll down, it should only be about 60-80px

2020-11-13 01:39 UTC, hanif-arif commented
When user clicks on Navbar, the navbar should highlight the selected section

2020-11-13 01:43 UTC, hanif-arif requested changes

2020-11-13 01:43 UTC, hanif-arif commented on src/components/Navbar.js
> +const Navbar = () => (
Track state of selected menu and highlight the selected menu

2020-11-13 01:43 UTC, hanif-arif commented on src/pages/contacts.styled.jsx
> +export const ButonCon = styled.button`
StyledButton

2020-11-13 01:45 UTC, hanif-arif commented
@LAEEQ18 you also have alot of warnings in the console that need to be cleared
![image](https://user-images.githubusercontent.com/73408406/99018420-fdfb7700-2527-11eb-8fc2-871763c2fc52.png)

2020-11-13 09:15 UTC, LAEEQ18 commented
> When user clicks on Navbar, the navbar should highlight the selected section

yes but for one click dont'know why this were not enabled on 2 click  it get sleceted i also give him active class

2020-11-13 10:34 UTC, LAEEQ18 commented on src/components/layout.js
> +const layout = ({ children }) => (
if using Layout then it will give error on **Children** prop Error

2020-11-13 11:07 UTC, LAEEQ18 commented on src/components/layout.js
> +const layout = ({ children }) => (
Layout = ({ children })
**'children' is missing in props validation**
so i use
```suggestion
const layout = ({ children }) => (

```

2020-11-14 10:26 UTC, LAEEQ18 commented on src/components/Navbar.js
> +const Navbar = () => (
the selected state is now highlited

2020-11-15 05:15 UTC, hanif-arif approved these changes

2020-11-15 05:15 UTC, merged